/**
	* Copyright (C) 2026 Indonesia Chip Design Collaborative Center (ICDEC)
	*
	* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
	* EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
	* OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
	* NONINFRINGEMENT.
	*/

/* platform-dependent definition of board */

#ifndef __VARIANTS_BOARDS_SOFT_PULPISSIMO_PYNQ_Z1_H__
#define __VARIANTS_BOARDS_SOFT_PULPISSIMO_PYNQ_Z1_H__

/* available LED definion for soft-pulpissimo PYNQ-Z1 */

#define BOARD_LED0_PAD_MUX_INDEX         5
#define BOARD_LED0_PAD_MUX_VALUE         2
#define BOARD_LED0_GPIO_INDEX            5

#define BOARD_LED1_PAD_MUX_INDEX         9
#define BOARD_LED1_PAD_MUX_VALUE         2
#define BOARD_LED1_GPIO_INDEX            9

#define BOARD_LED2_PAD_MUX_INDEX        10
#define BOARD_LED2_PAD_MUX_VALUE         2
#define BOARD_LED2_GPIO_INDEX           10

#define BOARD_LED3_PAD_MUX_INDEX        11
#define BOARD_LED3_PAD_MUX_VALUE         2
#define BOARD_LED3_GPIO_INDEX           11


#define BOARD_LED4_RED_PAD_MUX_INDEX    22
#define BOARD_LED4_RED_PAD_MUX_VALUE     2
#define BOARD_LED4_RED_GPIO_INDEX       22

#define BOARD_LED4_GREEN_PAD_MUX_INDEX  19
#define BOARD_LED4_GREEN_PAD_MUX_VALUE   2
#define BOARD_LED4_GREEN_GPIO_INDEX     19

#define BOARD_LED4_BLUE_PAD_MUX_INDEX   18
#define BOARD_LED4_BLUE_PAD_MUX_VALUE    2
#define BOARD_LED4_BLUE_GPIO_INDEX      18


#define BOARD_LED5_RED_PAD_MUX_INDEX    25
#define BOARD_LED5_RED_PAD_MUX_VALUE     2
#define BOARD_LED5_RED_GPIO_INDEX       25

#define BOARD_LED5_GREEN_PAD_MUX_INDEX  24
#define BOARD_LED5_GREEN_PAD_MUX_VALUE   2
#define BOARD_LED5_GREEN_GPIO_INDEX     24

#define BOARD_LED5_BLUE_PAD_MUX_INDEX   23
#define BOARD_LED5_BLUE_PAD_MUX_VALUE    2
#define BOARD_LED5_BLUE_GPIO_INDEX      23

/* definion for led BOARD_LED_BUILTIN */
#ifndef BOARD_LED_BUILTIN
#define BOARD_LED_BUILTIN   BOARD_LED1_GPIO_INDEX
#endif /* ! defined(BOARD_LED_BUILTIN) */

#endif /* ! defined(__VARIANTS_BOARDS_SOFT_PULPISSIMO_PYNQ_Z1_H__) */
